import {readiness,alternatives,validateSaved} from './engine.mjs';
const $=s=>document.querySelector(s), e=s=>String(s??'').replace(/[&<>"']/g,c=>`&#${c.charCodeAt(0)};`);let data,cues,selected,history=[];const key='prop-room-v1';
function note(t){$('#notice').hidden=false;$('#notice').textContent=t}
function save(){try{localStorage.setItem(key,JSON.stringify({version:1,cues}));$('#saved').textContent='Saved in this browser.'}catch{note('Storage unavailable. Print your plan before leaving.');$('#saved').textContent='Not saved.'}}
function change(fn){history.push(structuredClone(cues));fn();save();render()}
function options(items,id){return items.map(p=>`<option value="${e(p._id)}" ${p._id===id?'selected':''}>${e(p.title)}</option>`).join('')}
function render(){let r=readiness(cues,data.props);$('#issue-count').textContent=r.issues.length;$('#issue-label').textContent=r.issues.length?'conflicts to rehearse':r.ready?'Ready for the wings':'No timing conflicts';$('#summary-text').textContent=r.issues.length?'Find a spare prop or allow more reset time.':'Confirm each handoff, then print the crew sheet.';$('#confirmed').textContent=`${r.confirmed} of ${cues.length} handoffs confirmed`;$('#review').disabled=r.ready;$('#review').textContent=r.issues.length?'Review next conflict →':'Review next handoff →';$('#undo').disabled=!history.length;
$('#cues').innerHTML=data.scenes.map(s=>`<div class="scene-heading">${e(s.title)}</div>`+cues.filter(c=>c.sceneId===s._id).sort((a,b)=>a.start-b.start).map(c=>{let bad=r.issues.some(i=>i.cueId===c._id||i.previousId===c._id);return `<button class="cue ${selected===c._id?'selected':''} ${bad?'problem':''}" data-id="${e(c._id)}"><span class="cue-time">${c.start}–${c.end}</span><span><strong>${e(c.title)}</strong><small>${e(data.props.find(p=>p._id===c.propId)?.title)} · ${e(c.crew)}</small></span><span class="indicator">${bad?'!':c.confirmed?'✓':'○'}</span></button>`}).join('')).join('');$('#cues').querySelectorAll('button').forEach(b=>b.onclick=()=>{selected=b.dataset.id;render()});
$('#props').innerHTML=data.props.map(p=>`<div class="prop"><div class="prop-art" aria-hidden="true">${p.kind==='umbrella'?'☂':p.kind==='lantern'?'♧':'✉'}</div><strong>${e(p.title)}</strong><p>${e(p.description||p.kind)}</p><span class="reset">${p.resetMinutes} min reset · ${cues.filter(c=>c.propId===p._id).length} cues</span></div>`).join('');
let c=cues.find(c=>c._id===selected);if(!c){selected=cues[0]._id;c=cues[0]}let issues=r.issues.filter(i=>i.cueId===c._id||i.previousId===c._id);
$('#detail').innerHTML=`<p class="eyebrow">BACKSTAGE HANDOFF</p><h2>${e(c.title)}</h2><span class="tag ${issues.length?'':'good'}">${issues.length?'TIMING NEEDS ATTENTION':c.confirmed?'HANDOFF CONFIRMED':'READY TO REHEARSE'}</span>${issues.map(i=>`<div class="conflict"><strong>Timing conflict</strong><p>${e(i.message)}</p></div>`).join('')}${issues.length?alternatives(c,cues,data.props).map(p=>`<button class="swap" data-prop="${e(p._id)}">Use ${e(p.title)} →<small>Same type. Clear at this cue.</small></button>`).join(''):''}<form id="edit"><label>Assigned prop<select name="propId">${options(data.props,c.propId)}</select></label><div class="form-row"><label>Start minute<input name="start" type="number" min="0" max="239" required value="${c.start}"></label><label>End minute<input name="end" type="number" min="1" max="240" required value="${c.end}"></label></div><label>Crew<input name="crew" required maxlength="60" value="${e(c.crew)}"></label><label>Handoff side<select name="location">${['Stage left','Stage right','Upstage'].map(x=>`<option ${x===c.location?'selected':''}>${x}</option>`).join('')}</select></label><p id="error" role="alert"></p><button class="primary">Save rehearsal changes →</button></form><label class="confirm"><input id="confirm" type="checkbox" ${c.confirmed?'checked':''} ${issues.length?'disabled':''}>Crew and prop ready at handoff</label><p class="detail-note">Rehearsal edits stay in this browser. Shared Sanity records stay unchanged.</p>`;
$('#edit').onsubmit=ev=>{ev.preventDefault();let f=Object.fromEntries(new FormData(ev.target));f.start=Number(f.start);f.end=Number(f.end);if(f.end<=f.start){$('#error').textContent='End must follow start.';return}change(()=>Object.assign(c,f,{confirmed:false}))};$('#confirm').onchange=ev=>change(()=>c.confirmed=ev.target.checked);$('#detail').querySelectorAll('[data-prop]').forEach(b=>b.onclick=()=>change(()=>{c.propId=b.dataset.prop;c.confirmed=false}));}
$('#help').onclick=()=>$('#guide').showModal();document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('#review').onclick=()=>{let r=readiness(cues,data.props);selected=r.issues[0]?.cueId||cues.find(c=>!c.confirmed)?._id;render();$('#detail').scrollIntoView({behavior:'smooth',block:'center'})};$('#undo').onclick=()=>{cues=history.pop();save();render()};$('#reset').onclick=()=>{if(confirm('Reset your local rehearsal? Undo restores it.'))change(()=>cues=structuredClone(data.cues))};$('#add').onclick=()=>$('#add-dialog').showModal();$('#add-form').onsubmit=ev=>{ev.preventDefault();let c=Object.fromEntries(new FormData(ev.target));c.start=Number(c.start);c.end=Number(c.end);if(c.end<=c.start||cues.length>=100){$('#add-error').textContent='Check cue times. Maximum 100 cues.';return}c._id=crypto.randomUUID();c.confirmed=false;change(()=>{cues.push(c);selected=c._id});$('#add-dialog').close();ev.target.reset()};
$('#export').onclick=()=>{document.querySelector('.print-sheet')?.remove();let s=document.createElement('section');s.className='print-sheet';let r=readiness(cues,data.props);s.innerHTML=`<h1>Prop Room / crew sheet</h1><p>${e(data.production.title)} · Local rehearsal<br>${r.issues.length} unresolved conflicts · ${r.confirmed}/${cues.length} handoffs confirmed</p><table><tr><th>Minute</th><th>Cue / prop</th><th>Crew / side</th><th>Handoff</th></tr>${[...cues].sort((a,b)=>a.start-b.start).map(c=>`<tr><td>${c.start}–${c.end}</td><td>${e(c.title)}<br>${e(data.props.find(p=>p._id===c.propId)?.title)}</td><td>${e(c.crew)} / ${e(c.location)}</td><td>${c.confirmed?'Confirmed':'Unconfirmed'}</td></tr>`).join('')}</table><h2>Reset notes</h2><p>${data.props.map(p=>`${e(p.title)}: ${p.resetMinutes} min`).join(' · ')}</p>${r.issues.map(i=>`<p>${e(i.message)}</p>`).join('')}`;document.querySelector('main').append(s);window.print()};
async function init(){let live=true;try{let q='{"production":*[_id=="production-last-platform"][0],"props":*[_type=="prop"],"scenes":*[_type=="scene"]|order(order asc),"cues":*[_type=="cue"]{...,"propId":prop._ref,"sceneId":scene._ref}|order(start asc)}';let res=await fetch('https://gdohz22j.api.sanity.io/v2025-02-19/data/query/production?query='+encodeURIComponent(q),{signal:AbortSignal.timeout(8000)});if(!res.ok)throw Error();data=(await res.json()).result;if(!data.cues?.length)throw Error()}catch{live=false;data=await(await fetch('/seed.json')).json();note('Sanity could not be reached. Bundled sample loaded instead.')}cues=structuredClone(data.cues);try{let raw=localStorage.getItem(key);if(raw){let saved=validateSaved(JSON.parse(raw),data);if(saved)cues=saved;else note('Saved rehearsal was incompatible. Published sample loaded.')}}catch{note('Saved rehearsal could not be read. Published sample loaded.')}selected=cues[0]._id;$('#source').textContent=live?'Published cues from Sanity · local rehearsal':'Offline sample · local rehearsal';$('#new-scene').innerHTML=options(data.scenes);$('#new-prop').innerHTML=options(data.props);render()}
init().catch(()=>note('Sample could not load. Refresh to retry.'));
